from datetime import date
from pathlib import Path
from typing import Optional


def _fmt_market_cap(billions: Optional[float]) -> str:
    if billions is None:
        return "N/A"
    if billions >= 1000:
        return f"${billions / 1000:.1f}T"
    return f"${billions:.1f}B"


def _fmt_pct(value: Optional[float]) -> str:
    if value is None:
        return "N/A"
    sign = "+" if value > 0 else ""
    return f"{sign}{value:.1f}%"


def _fmt_pe(value) -> str:
    if isinstance(value, (int, float)):
        return f"{value:.1f}x"
    return "N/A"


def _fmt_vol(millions: Optional[float]) -> str:
    if millions is None:
        return "N/A"
    return f"{millions:.1f}M"


def render_report(result: dict, strategy_name: str, run_date: str) -> str:
    stocks = result.get("stocks", [])
    lines: list[str] = []

    lines += [
        "# AI Stock Advisor Report",
        "",
        f"**Date**: {run_date}  ",
        f"**Strategy**: {strategy_name}  ",
        "**Universe**: S&P 500  ",
        "",
        "---",
        "",
        "## Market Context",
        "",
        result.get("market_context", ""),
        "",
        f"**Strategy Application**: {result.get('strategy_summary', '')}",
        "",
        "---",
        "",
        "## Top 10 Stocks - Summary Table",
        "",
        "| # | Ticker | Name | Sector | Price | Mkt Cap | P/E | Avg Vol | Action |",
        "|---|--------|------|--------|-------|---------|-----|---------|--------|",
    ]

    for s in stocks:
        rank = s.get("rank", "")
        ticker = s.get("ticker", "")
        name = (s.get("name") or "")[:28]
        sector = (s.get("sector") or "")[:22]
        price = f"${s['price']:.2f}" if s.get("price") else "N/A"
        mkt = _fmt_market_cap(s.get("market_cap_billions"))
        pe = _fmt_pe(s.get("pe_ratio"))
        vol = _fmt_vol(s.get("avg_volume_millions"))
        action = s.get("action", "WATCH")
        lines.append(
            f"| {rank} | **{ticker}** | {name} | {sector} | {price} | {mkt} | {pe} | {vol} | **{action}** |"
        )

    lines += ["", "---", "", "## Individual Stock Analysis", ""]

    for s in stocks:
        ticker = s.get("ticker", "")
        name = s.get("name", "")
        action = s.get("action", "WATCH")
        price_str = f"${s['price']:.2f}" if s.get("price") else "N/A"
        pe_str = _fmt_pe(s.get("pe_ratio"))
        mkt_str = _fmt_market_cap(s.get("market_cap_billions"))
        metrics = s.get("key_metrics") or {}

        lines += [
            f"### {s.get('rank', '')}. {ticker} - {name}",
            "",
            f"**Action**: **{action}** | "
            f"**Sector**: {s.get('sector', 'N/A')} | "
            f"**Price**: {price_str} | "
            f"**P/E**: {pe_str} | "
            f"**Mkt Cap**: {mkt_str}",
            "",
            "#### Investment Thesis",
            "",
            s.get("thesis", ""),
            "",
            "#### Key Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Revenue Growth (YoY) | {_fmt_pct(metrics.get('revenue_growth_pct'))} |",
            f"| Net Margin | {_fmt_pct(metrics.get('net_margin_pct'))} |",
            f"| Debt / Equity | {metrics.get('debt_to_equity', 'N/A')} |",
            f"| 6-Month Price Change | {_fmt_pct(metrics.get('change_6mo_pct'))} |",
            f"| 1-Year Price Change | {_fmt_pct(metrics.get('change_1y_pct'))} |",
            f"| Dividend Yield | {_fmt_pct(metrics.get('dividend_yield_pct'))} |",
            "",
            "#### Risk Factors",
            "",
            s.get("risk_factors", ""),
            "",
            "---",
            "",
        ]

    lines += [
        "## Portfolio Summary",
        "",
        result.get("summary", ""),
        "",
        "---",
        f"*Generated by AI Stock Advisor on {run_date}. This report is for informational purposes only and does not constitute financial advice.*",
    ]

    return "\n".join(lines)


def save_report(result: dict, strategy_name: str) -> str:
    """Render and save the report. Returns the file path."""
    run_date = date.today().isoformat()
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    filepath = reports_dir / f"report_{run_date}.md"
    filepath.write_text(render_report(result, strategy_name, run_date), encoding="utf-8")
    return str(filepath)
